### ISSUE TITLE
REL1_39 branch - SpecialSearchDigest.php incorrectly uses "MediaWiki\Title\Title" when it should just be "Title"

### ISSUE THREAD

**Issue by MelvorIdle** [weirdgloop/mediawiki-extensions-SearchDigest#12]
Hello,

We had trouble loading the Special:SearchDigest page on our Wiki that is using the 1.39 release candidate. After some investigation, we found that `SpecialSearchDigest.php` uses an incorrect class for the respective MediaWiki version.

SpecialSearchDigest.php : Line 11
```php
use MediaWiki\Title\Title;
```

Should be
```php
use Title;
```

This is specifically for the REL1_39 branch.

MediaWiki reference: https://www.mediawiki.org/wiki/Manual:Title.php

**Comment by alistair3149** [comment]
The `MediaWiki\Title\Title` class alias is added [since MediaWiki 1.39.4](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/REL1_39/RELEASE-NOTES-1.39#184), so it is technically correct for the `REL1_39` branch as it only requires to maintain compatibility for the latest 1.39.x release.

The solution can either be changing back to the older class in the `REL1_39` branch of the extension to support < 1.39.4, or you can update pass 1.39.4 (the latest patch release is 1.39.7).

**Comment by jayktaylor** [comment]
Hey @MelvorIdle, I've pushed https://github.com/weirdgloop/mediawiki-extensions-SearchDigest/commit/e1ccf249eb9c1ec5c83c041efe4cdc8187aa3544 to the REL1_39 branch which should fix this issue. As mentioned above, 1.39.4 does add support for `MediaWiki\Title\Title`, but it seems easier to change the extension code so that it would work across all 1.39 versions.
