### ISSUE TITLE
Suggestion | Add page to Watchlist

### ISSUE THREAD

**Issue by azgoodaz** [weirdgloop/mediawiki-extensions-SearchDigest#17]
Given that the list can't email you when a link or search term is generated, would it be possible to "subscribe" / add page to watchlist so users are notified if a term is searched but wasn't found by user.

There are times where you can't see this data weekly and it gets either refreshed or deleted so having this as a reminder would be nice to have.

**Comment by jayktaylor** [comment]
Thanks for the suggestion. I think we'll probably pass on adding this to the extension because it would add additional complexity and likely require new database tables for tracking.

I think that having some kind of watchlist would also be very likely to lead to users receiving spammy notifications, and therefore it would not be as useful as we'd like.
